##In-Class Assignment - Movie Night

In [2]:
# Run me first!
my_name = "Nathnael Abraham"
todays_date = "2026-09-22"

print("Notebook by:", my_name)
print("Date:", todays_date)
print("Let's go! 🍿")

Notebook by: Nathnael Abraham
Date: 2026-09-22
Let's go! 🍿

##1. Variables

In [4]:
# Create these variables about your FAVORITE movie:
# favorite_movie  -> the title, as text (a string)
favorite_movie = "Maze Runner"
# release_year    -> the year it came out, a whole number
release_year = 2014
# my_rating       -> your rating out of 10, a decimal like 8.5
my_rating = 10
# have_seen_twice -> True or False, have you watched it more than once?
have_seen_twice = True

# YOUR CODE HERE


# The line below prints them. It will work once you've made the variables above.
print(favorite_movie, "came out in", release_year)
print("My rating:", my_rating, "/ 10")
print("Seen it twice?", have_seen_twice)

Maze Runner came out in 2014
My rating: 10 / 10
Seen it twice? True

##2. Data Structures: Lists & Dictionaries

In [5]:
movies = [
    {"title": "The Matrix",        "year": 1999, "rating": 8.7, "genre": "Sci-Fi"},
    {"title": "Toy Story",         "year": 1995, "rating": 8.3, "genre": "Animation"},
    {"title": "Parasite",          "year": 2019, "rating": 8.5, "genre": "Thriller"},
    {"title": "Spirited Away",     "year": 2001, "rating": 8.6, "genre": "Animation"},
    {"title": "The Dark Knight",   "year": 2008, "rating": 9.0, "genre": "Action"},
    {"title": "Get Out",           "year": 2017, "rating": 7.7, "genre": "Thriller"},
    {"title": "La La Land",        "year": 2016, "rating": 8.0, "genre": "Musical"},
    {"title": "Interstellar",      "year": 2014, "rating": 8.7, "genre": "Sci-Fi"},
]

print("We have", len(movies), "movies loaded.")
movies[0]  # peek at the first one

We have 8 movies loaded.

{'title': 'The Matrix', 'year': 1999, 'rating': 8.7, 'genre': 'Sci-Fi'}

In [10]:
# 1) Print the title of the FIRST movie in the list.
print(movies[0]["title"])

# 2) Print the rating of the LAST movie in the list.
print(movies[-1]["rating"])

The Matrix
8.7

##3. Loops

In [12]:
# Loop over every movie and print: "Title (year) — rating X"
for movie in movies:
  print(movie["title"], "(", movie["year"], ") - rating", movie["rating"])

The Matrix ( 1999 ) - rating 8.7
Toy Story ( 1995 ) - rating 8.3
Parasite ( 2019 ) - rating 8.5
Spirited Away ( 2001 ) - rating 8.6
The Dark Knight ( 2008 ) - rating 9.0
Get Out ( 2017 ) - rating 7.7
La La Land ( 2016 ) - rating 8.0
Interstellar ( 2014 ) - rating 8.7

##4. Conditionals

In [15]:
# Loop through movies and print each title with its label.

for movie in movies:
  if movie["rating"] >= 9.0:
    print(movie["title"], "- Masterpiece")
  elif movie["rating"] >= 8.0:
    print(movie["title"], "- Great")
  else:
    print(movie["title"], "- Good")

The Matrix - Great
Toy Story - Great
Parasite - Great
Spirited Away - Great
The Dark Knight - Masterpiece
Get Out - Good
La La Land - Great
Interstellar - Great

##5. List Comprehension

In [16]:
# 1) A list of ALL genres (may include duplicates).
all_genres = [movie["genre"] for movie in movies]
print("Genres:", all_genres)

# 2) A list of titles for movies rated 8.5 or higher.
top_titles = [movie["title"] for movie in movies if movie["rating"] >= 8.5]
print("Top rated:", top_titles)

# 3) A list of titles from movies made in the year 2000 or LATER.
this_century = [movie["title"] for movie in movies if movie ["year"] >= 2000]
print("2000 and later:", this_century)

Genres: ['Sci-Fi', 'Animation', 'Thriller', 'Animation', 'Action', 'Thriller', 'Musical', 'Sci-Fi']
Top rated: ['The Matrix', 'Parasite', 'Spirited Away', 'The Dark Knight', 'Interstellar']
2000 and later: ['Parasite', 'Spirited Away', 'The Dark Knight', 'Get Out', 'La La Land', 'Interstellar']

##6. Functions

In [17]:
def describe_movie(movie):
    # Should return a string like:
    # "The Matrix is a Sci-Fi film from 1999 rated 8.7"
    # Use the movie's "title", "genre", "year", and "rating" keys.
    return movie["title"] + " is a " + movie["genre"] + " film from " + str(movie["year"]) + " rated " + str(movie["rating"])
    pass


# Test it (this should print a full sentence, not "None"):
print(describe_movie(movies[0]))
print(describe_movie(movies[2]))

The Matrix is a Sci-Fi film from 1999 rated 8.7
Parasite is a Thriller film from 2019 rated 8.5

In [20]:
def average_rating(movie_list):
    # Add up every movie's rating, then divide by how many there are.
    # Hint: len(movie_list) tells you how many movies there are.
    total = 0
    for movie in movie_list:
      total = total + movie["rating"]
    return total / len(movie_list)
    pass


print("Average rating:", average_rating(movies))

Average rating: 8.4375

##7. Lambda Functions

In [24]:
# Sort movies by rating, HIGHEST first (descending).
# Fill in the lambda so it returns each movie's rating.
movies_by_rating = sorted(movies, key=lambda m:m["rating"], reverse=True)  # replace ___

for m in movies_by_rating:
    print(m["rating"], m["title"])

9.0 The Dark Knight
8.7 The Matrix
8.7 Interstellar
8.6 Spirited Away
8.5 Parasite
8.3 Toy Story
8.0 La La Land
7.7 Get Out

##8. Intro To Pandas

In [25]:
import pandas as pd

df = pd.DataFrame(movies)
df

             title  year  rating      genre
0       The Matrix  1999     8.7     Sci-Fi
1        Toy Story  1995     8.3  Animation
2         Parasite  2019     8.5   Thriller
3    Spirited Away  2001     8.6  Animation
4  The Dark Knight  2008     9.0     Action
5          Get Out  2017     7.7   Thriller
6       La La Land  2016     8.0    Musical
7     Interstellar  2014     8.7     Sci-Fi

In [26]:
# 1) Show just the "title" and "rating" columns.
#    Hint: df[["title", "rating"]]
df[["title", "rating"]]


# 2) The average rating of the whole column, the easy way:
print("Mean rating:", df["rating"].mean())

# 3) Only the rows where genre is "Animation".
#    Hint: df[df["genre"] == "Animation"]
df[df["genre"] == "Animation"]

Mean rating: 8.4375

           title  year  rating      genre
1      Toy Story  1995     8.3  Animation
3  Spirited Away  2001     8.6  Animation

##9. Working with API Data

In [27]:
# This is a pretend API response (already parsed into a Python dictionary).
api_response = {
    "status": "ok",
    "results": [
        {"name": "Dune: Part Two", "year": 2024, "score": 8.5},
        {"name": "Everything Everywhere All at Once", "year": 2022, "score": 7.8},
        {"name": "Oppenheimer", "year": 2023, "score": 8.3},
    ],
}

print("Status:", api_response["status"])
print("Number of results:", len(api_response["results"]))

Status: ok
Number of results: 3

In [28]:
# 1) Print the "name" of every movie in the API results (use a loop).
for movie in api_response["results"]:
  print(movie["name"])


# 2) Turn the API results into a pandas DataFrame and display it.
#    Hint: pd.DataFrame(api_response["results"])
api_df = pd.DataFrame(api_response["results"])
api_df

Dune: Part Two
Everything Everywhere All at Once
Oppenheimer

                                name  year  score
0                     Dune: Part Two  2024    8.5
1  Everything Everywhere All at Once  2022    7.8
2                        Oppenheimer  2023    8.3

##10. Save Data & Push to Github

In [29]:
# Save the movies table to a CSV file (no extra index column).
df.to_csv("movies.csv", index=False)
print("Saved movies.csv ✅  (look in the file browser on the left)")

Saved movies.csv ✅  (look in the file browser on the left)